#!/bin/sh

export DOTFILESDIR=${PWD}

# Backup and restore .zshrc 
ZSHRC=$HOME/.zshrc
if [  -e "$ZSHRC" ]; then 
	mv $HOME/.zshrc $HOME/.zshrc.backup
fi
ln -s $DOTFILESDIR/.zshrc $ZSHRC

# Backup and apply .vimrc
VIMRC=$HOME/.vimrc
if [  -e "$VIMRC" ]; then 
	mv $VIMRC $HOME/.vimrc.backup
fi
ln -s $DOTFILESDIR/.vimrc $VIMRC

# Backup and restore tmux
mv $HOME/.config/tmux $HOME/.config/tmux.backup
ln -s $DOTFILESDIR/tmux $HOME/.config/

# Backup and replace .gitconfig
mv $HOME/.gitconfig $HOME/.gitconfig.backup
ln -s $DOTFILESDIR/.private.rc/.gitconfig $HOME/.gitconfig

# Install tmux plugin manager if not already done
TMP_DIR=$DOTFILESDIR/tmux/plugins/tpm
if [ ! -d "$TMP_DIR" ]; then
	echo "Cloning TMUX plugin manager..."
	git clone https://github.com/tmux-plugins/tpm $DOTFILESDIR/tmux/plugins/tpm
	echo "\033[0;33mPlease open tmux and press prefix+I to complete installation\033[0m"
else
	echo "TMUX plugin manager already installed."
fi

